SELECT DISTINCT CRCC.CAR_ID, 
CRCC.CAR_TYPE, 
FLOOR(CRCC.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID=CRCRH.CAR_ID 
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP ON CRCC.CAR_TYPE=CRCDP.CAR_TYPE 
AND CRCDP.DURATION_TYPE='30일 이상' AND (CRCDP.CAR_TYPE='세단' OR CRCDP.CAR_TYPE='SUV')
WHERE FLOOR(CRCC.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE) / 100) BETWEEN 499999 AND 2000000 - 1 
    AND CRCC.CAR_ID NOT IN (SELECT CAR_ID
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                            WHERE (START_DATE < '2022-11-30' 
                                   AND END_DATE > '2022-11-01'))
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC;