# 날짜 비교 예시
# (h.END_DATE-h.START_DATE) 
# DATEDIFF(h.END_DATE, h.START_DATE) 
# TIMESTAMPDIFF(DAY, h.START_DATE, h.END_DATE) 

SELECT 
    h.CAR_ID, 
    ROUND(AVG(TIMESTAMPDIFF(DAY, h.START_DATE, h.END_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
GROUP BY h.CAR_ID
HAVING  AVERAGE_DURATION >= 7
ORDER BY 2 DESC, 1 DESC ;