-- 코드를 입력하세요
# JOIN을 사용한 답안.
SELECT f.FLAVOR
FROM FIRST_HALF AS f
JOIN ICECREAM_INFO AS i ON i.FLAVOR = f.FLAVOR
# JOIN ICECREAM_INFO AS i USING(FLAVOR)
WHERE TOTAL_ORDER > 3000 && INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC