SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK AS b
INNER JOIN BOOK_SALES AS bs ON b.BOOK_ID=bs.BOOK_ID
# WHERE bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
WHERE YEAR(bs.SALES_DATE)=2022 AND MONTH(bs.SALES_DATE)=1
GROUP BY b.CATEGORY 
ORDER BY 1;


